Repository iterative/datachain, pull requests merged in 2024-12, with the labels that each got.

#672 chore: update readme
  README.rst
Labels: documentation

#670 feat: update documentation and enhance navigation structure
  CONTRIBUTING.rst
  README.rst
  docs/contributing.md
  docs/examples.md
  docs/index.md
  docs/quick-start.md
  docs/references/index.md
  docs/tutorials.md
  mkdocs.yml
Labels: documentation

#667 Allow testing external contributions using secrets
  .github/workflows/tests.yml
Labels: tests

#673 chore: follow up docs navigation update
  docs/contributing.md
  docs/css/github-permalink-style.css
  docs/examples.md
  docs/index.md
  docs/quick-start.md
  docs/references/index.md
  docs/tutorials.md
  mkdocs.yml
Labels: documentation

#726 fix(listing): pick exact or create new one on update
  src/datachain/lib/dc.py
  tests/func/test_catalog.py
  tests/unit/test_listing.py
Labels: bug

#732 fix(dc): move parse uri and rename out of main class
  src/datachain/catalog/catalog.py
  src/datachain/lib/dc.py
  src/datachain/lib/listing.py
  tests/unit/test_listing.py
Labels: housekeeping

#735 Fix Mistral example in quick-start
  docs/quick-start.md
Labels: p0-critical

#734 fix(from_storage): no listing / cache on a single file
  src/datachain/catalog/catalog.py
  src/datachain/catalog/datasource.py
  src/datachain/client/fsspec.py
  src/datachain/dataset.py
  src/datachain/lib/dc.py
  src/datachain/lib/listing.py
  src/datachain/listing.py
  src/datachain/node.py
  tests/func/test_catalog.py
  tests/func/test_datachain.py
  tests/unit/test_listing.py
Labels: enhancement

#753 fix(cache, client): support versioned files
  src/datachain/cache.py
  src/datachain/client/fsspec.py
  src/datachain/client/gcs.py
  src/datachain/client/local.py
  tests/func/test_catalog.py
  tests/func/test_pull.py
Labels: bug

#755 Fix signed url versioning
  pyproject.toml
  src/datachain/catalog/catalog.py
  src/datachain/client/azure.py
  src/datachain/client/fsspec.py
  src/datachain/client/gcs.py
  src/datachain/client/s3.py
  tests/func/fake-service-account-credentials.json
  tests/func/test_catalog.py
  tests/unit/test_client_gcs.py
  tests/unit/test_client_s3.py
Labels: enhancement

#766 fix: better message if no files passed on parse tabular
  src/datachain/lib/arrow.py
  src/datachain/lib/dc.py
  tests/unit/lib/test_arrow.py
  tests/unit/lib/test_datachain.py
Labels: enhancement
