Repository iterative/datachain, pull requests merged in 2024-08, with the labels that each got.

#241 fix(to_pandas): handle empty datachain in to_pandas (and show)
  src/datachain/lib/dc.py
  tests/func/test_datachain.py
  tests/unit/lib/test_datachain.py
Labels: bug

#314 add_regexp_replace
  src/datachain/sql/functions/string.py
  src/datachain/sql/sqlite/base.py
  tests/unit/sql/test_string.py
Labels: enhancement

#319 Support all column types in SignalSchema.from_column_types
  src/datachain/lib/convert/flatten.py
  src/datachain/lib/signal_schema.py
  src/datachain/sql/types.py
  tests/unit/lib/test_signal_schema.py
Labels: bug

#330 use default delimiter to flatten columns
  src/datachain/lib/dc.py
  tests/unit/lib/test_datachain.py
Labels: bug

#356 slight positioning change to deny AI abstractions
  README.rst
Labels: documentation
