Repository iterative/datachain, pull requests merged in 2025-01, with the labels that each got.

#774 fix(navigation): lock mkdocs-material version
  mkdocs.yml
  pyproject.toml
Labels: documentation

#777 feat(signal schema): serialize base classes for custom types
  src/datachain/lib/signal_schema.py
  tests/unit/lib/test_signal_schema.py
Labels: bug

#804 fix(schema): reconnect closed connection
  src/datachain/data_storage/db_engine.py
  src/datachain/data_storage/schema.py
  src/datachain/data_storage/sqlite.py
  src/datachain/data_storage/warehouse.py
  tests/func/test_datachain.py
Labels: bug

#813 Add CSV parsing options
  src/datachain/lib/dc.py
  tests/unit/lib/test_datachain.py
Labels: enhancement
